### PR TITLE
Don't compile higher dimensional classes unless asked

### PR DESCRIPTION
**Pull request by WPettersson**
Adds a new HIGHDIM option to cmake. By default, the higher dimensional
(dim5 and higher) objects are not compiled. To add these, run cmake with
-DHIGHDIM.

- Avoids explicitly instantiating the higher dimensional classes
- Removes their packet types
- Remove from Python interface
- Remove from GUI
- Remove from C++ testing

Current issues:
- The Python tests will fail, as they assume the availability of these higher dimensional classes. I don't see an immediate and simple fix, so I wanted to see if others had any good ideas. 

It's also set to current not compile the higher-dimensional objects by default. This will mean adding a flag to cmake (-DHIGHMEM) for distributions. I don't know whether it's best to have this as default-on, or default-off, but it's fairly easy to switch up.

### CODE REVIEW

**Comment by baburton** [comment]
What’s the motivation here?  (Compile time?  File size?)

Personally, I’d be much more comfortable with this if all dimensions were the default, and this were an option to restrict the build to low dimensions only.  (Partly for backward compatibility - the high dimensional code is already released - and partly because people who don’t know what they’re doing will build with the defaults first and tinker later.)

- b.

**Comment by WPettersson** [comment]
The motivation is mainly compile time. On my laptop (with a measly 2GB of RAM), compiles tend to almost completely stall on the higher dimensional objects, with some files (dimensions 12 and above) taking 4-5 minutes each to compile, and leaving my laptop unusable whilst doing so.

I've switched things over so by default, everything is compiled. The option is also marked INTERNAL, making it less likely for users to stumble across it.

**Comment by baburton** [comment]
Hi - sorry for losing track of this.  I’ve gone over the lowdimonly branch and made a couple of changes:

- I changed HIGHDIM to LOWDIMONLY, so that if you pull a source file out of regina and try to build it with your own build system, then by default you get all of regina’s functionality.  (That is, you don’t need to pass a magic flag -DHIGHDIM in order to get default behaviour.)

- I had a look over the patches and I think it was pulling things out of the python bindings a bit too aggressively - things like FacetPairing in dimension 2 and 4, and things relating to face numbering.  See my last commit to the branch.

I have *not* tested it - I just made my patches and pushed again.  So please see if it still does what you wanted, but if it does then feel free to go ahead and merge it into master.

- b.

--

Prof. Benjamin Burton
Computational Geometry & Topology Group
School of Mathematics and Physics
The University of Queensland, Australia

**Comment by WPettersson** [comment]
I had to add a missing #endif but otherwise everything compiled, and the tests all ran fine (except the ones where the classes were missing, of course).

**Pull request merged**
