### PR TITLE
Ordered barycentric subdivision for any dimension

### PR DESCRIPTION
**Pull request by unhyperbolic**
The ordering of the simplicies is different from the old implementation.

Also: is it valid to call simplices._swap directly or should I instead create a new triangulation and call swapContents?

### CODE REVIEW

**Comment by unhyperbolic** [comment]
Just saw that you reworked my code and checked-it in. Looks great. Thank you!

**Comment by baburton** [comment]
A caveat, in case you need the exact labelling / ordering that your code had: it’s more like a hybrid of the two implementations:

- Its implementation is generic, but has a static_assert that limits it to standard dimensions (2,3,4).  This is due to the factorial explosion in size for higher dimensions (and indeed, for dimension 15 there is no guarantee that the number of simplices will fit into a size_t, if I’m not mistaken).

- The permutations are ordered lexicographically, not by the S2 / S3 / S4 indices (which my original implementations used).

- The labelling is closer to my original implementation, though the permutation is reversed to give a more sensible description as yours had - the vertices of the subsimplex indexed by p are now the centroids of faces p[0], p[0]-p[1], p[0]-p[1]-p[2], etc, and these vertices are labelled p[0], p[1], p[2], etc. respectively (whereas I think your implementation labelled them 0, 1, 2, etc.).

- Importantly, the ordering and labelling are now both promises in the API documentation, so as of the next release they will become more problematic to change again.

If you need to check properties of centroids of faces (that aren’t vertices), and the existing code doesn’t do what you need (e.g., through isValid, hasBadLink, etc.), then it’s probably best to implement the relevant test(s) directly without needing a barycentric subdivision - the latter is (IMHO) too expensive in higher dimensions, and not necessarily implementable in the highest dimensions that regina supports.

- b.

PS: My hitlist for the next release is very short now (tidy up some things in the iOS GUI and finish the class renaming in the subcomplex/ directory), so if there’s anything that’s important for you to push into the next release then speak now. :)  I hope to get it out before the year end.

--

A/Prof Benjamin Burton
Computational Geometry & Topology Group
School of Mathematics and Physics
The University of Queensland, Australia

**Comment by unhyperbolic** [comment]
Thanks for your message.


> - The labelling is closer to my original implementation, though the
> permutation is reversed to give a more sensible description as yours had -
> the vertices of the subsimplex indexed by p are now the centroids of faces
> p[0], p[0]-p[1], p[0]-p[1]-p[2], etc, and these vertices are labelled p[0],
> p[1], p[2], etc. respectively (whereas I think your implementation labelled
> them 0, 1, 2, etc.).
>

Maybe I should have given some more explanation why we like to get an
ordered triangulation (where the face identifications are order preserving,
what Hatcher calls a Delta complex): some homological constructions fail on
unordered triangulations. Easy enough to extend simplicial homology from
ordered triangulations to unordered ones, but how would you do that for,
e.g., Neumann's Extended Bloch group? It would be nice if barycentric
subdivision had the property of always producing an ordered triangulation
(even though in dimension 3, Neumann gives a more efficient method of
giving an ordered triangulation that has only 6 times as many simplicies).

That's why Christian Zickert and I regarded my implementation as more
natural than the labeling induced from the original triangulation.

The fact that you can easily tell from the label k of a vertex that it
belonged to a k-cell is an added bonus.

What is a benefit of the other way of labeling the vertices?


> - Importantly, the ordering and labelling are now both promises in the API
> documentation, so as of the next release they will become more problematic
> to change again.
>

In light of the above, not sure how I feel about that.

**Comment by unhyperbolic** [comment]
>
>
> PS: My hitlist for the next release is very short now (tidy up some things
> in the iOS GUI and finish the class renaming in the subcomplex/ directory),
> so if there’s anything that’s important for you to push into the next
> release then speak now. :) I hope to get it out before the year end.
>
>
A dimension type trait in python would be very useful, i.e.,
regina.Triangulation2.dimension would be 2, regina.Triangulation3.dimension
would be 3, ...

**Comment by baburton** [comment]
> What is a benefit of the other way of labeling the vertices?

One is orientation - if the original is oriented then so is the subdivision.  (I've had several requests over the years on the broader topic of preserving orientation - something Regina still does not do well.)

Btw, by locking down the API, I really mean preserving backward compatibility - so there's no problem with (for instance) later introducing an extra argument to describe the labelling that defaults to whatever is released with Regina 5.1.  The main issue is that calling barycentricSubdivision() in later versions with no arguments should still do whatever 5.1 does.

- b.

**Comment by baburton** [comment]
> A dimension type trait in python would be very useful, i.e.,
> regina.Triangulation2.dimension would be 2, regina.Triangulation3.dimension
> would be 3, …

Committed. - b.

**Comment by unhyperbolic** [comment]
Awesome! Thank you!

**Comment by unhyperbolic** [comment]
On Thu, Dec 8, 2016 at 10:30 AM, baburton <notifications@github.com> wrote:

>
> > What is a benefit of the other way of labeling the vertices?
>
> One is orientation - if the original is oriented then so is the
> subdivision. (I've had several requests over the years on the broader topic
> of preserving orientation - something Regina still does not do well.)
>

Good point. I see.


> Btw, by locking down the API, I really mean preserving backward
> compatibility - so there's no problem with (for instance) later introducing
> an extra argument to describe the labelling that defaults to whatever is
> released with Regina 5.1. The main issue is that calling
> barycentricSubdivision() in later versions with no arguments should still
> do whatever 5.1 does.


Then I am feeling happy with the current state of affairs.

**Pull request closed without merging**
